apiVersion: v1
kind: Pod
metadata:
  name: mariadb
  labels:
    name: mariadb
spec:
  containers:
  - name: mariadb
    image: $image
    ports:
      - containerPort: 3306
    env:
    - name: DBUSER
      value: $db_user
    - name: DBPASS
      value: $db_pass
    - name: DBNAME
      value: $db_name
